# fly.toml app configuration file generated for pds-gruen-lol on 2024-12-02T16:33:47-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pds-gruen-lol'
primary_region = 'ewr'

[build]
  image = 'ghcr.io/bluesky-social/pds:0.4'

[[mounts]]
  source = 'pds_data'
  destination = '/data'

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
